name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Example: Build your React app
          npm cache clean -f
          npm install -g npm
          npm install
          npm install
          npm run build

          # Deploy using the API key
          deploy-script.sh $API_KEY
